language: java
dist: trusty
jdk:
  - openjdk8
  - oraclejdk8
  - oraclejdk9
install: true
script:
    - "./gradlew clean"
    - "./gradlew exhaustiveTest"
    - "if [[ -n $TRAVIS_TAG ]]; then
          ./gradlew ship;
      else
          ./gradlew build;
      fi"
cache:
  gradle: true
  directories:
  - "$HOME/.gradle/caches"
  - "$HOME/.gradle/wrapper"
branches:
  only:
  - master
  - /^\d+\.\d+\.\d+(-SNAPSHOT|-alpha|-beta)?\d*$/ # trigger builds on tags which are semantically versioned to ship the SDK.
after_success:
  - ./gradlew coveralls uploadArchives --console plain
  - ./push-javadoc-to-gh-pages.sh
env:
    global:
    - secure: AscVURpguRPEklN23Y3XQ4mN6KqwW36DJsBMtVB9mxrKxcFlQu9kxNTO0OLoIBzuoKRVnQwxFWIxq0unSeQwRjfgpxS8mfe6UUutF8Zksj3YhAyNwlIG1DP38MDH5iX0NFEjARCfZgBqR0Uq6cS9i+vZLaTvITyQTkOEbrmvX1wn6xfk6F+h+k6k7mDsDwDx6DLluhGGVrJtnKJSd7WWOJfSQk7Qu6zyNs8mvkhueA2HxqB2gIjZwRZFSAsKOL4ZmkgWj46DsK6lkbwArCYwBN59d24A8ZE/OUq9ZkjU/NcWHqmDA93i/wXIBoaTXCMhZG+eJiswcTFSsWhbLVNxzllelr2UgdIzvQ10+L+iCCQoX0x+BHPybfdSRxDxETjd0bv8vh7CE9vNc1ZMT1gh3gLyjjBS1PGw8VmEvjlqV2tPzGZTdO/xD+3ENQBETfAJ8Vum43lNoyoqS9Svpe53coXUSh5J6I9ufnh477UHYB+tJ40hrklLV3puVvWHv/WdqHBfxpBj8ucom/OI9IpqxoNn5OadiqvueBVijE+UiOzv1nvR1j46H2Eqbe8RXnCeCdsX+UqpcnCTiXVYtNxvBCjD57B+cW6IHJf69JnY9i8lEc0RdZI8Fv7KuAN8yPfiZrKFrnO5x1NeYXa2z3g0wi2CWIbIJlf+cMcVprrpsFg=
    - secure: MdW7OyX7H3MjckrhEhuj4M97r7P1e2egg0UXzvG4t713rpXA9xGXMofdgsDx47/Tg5LlZYPyTunYGAPL8KdS/vXgNEQN9/ERIGl1cRl0bPT2o/+LfR2zqM5PjDDpReCpYLLKmsuU0Oo3W+Lf6ZjC/QuZX/z7X7d3SvZ9o+Aydlqij9KmMNBA6wxSMA5g0uX4Uc5BRpKfnrxOcpoJX2HUkxcSkjV73Hdzcg32/kEJRmPw2XBLcl6NXeNSA0OZKl/4tGJl3w66saseeQg3u66CUvMc5RhmRuNdobp2GrJ+8cRLcIop/KcSM8EnM4SpQdaspWynkeIk/SFfZCoDcOhWFcNWcmxUtNvu/SJPFvQiCHSqG3RjHl5s/r6BZQYfmY/DtMlquUJIgqWCfG69i6VTtNek3dcJDHkGb47yuaAdEVF3qpVALUFWSa26wNmjoMmwXJngOkazXWJs5nVGVXE+8DxBT8nO5Hxc5wMVSJeZAUIB4IzAQOzKiE0Z6DJ5//iJ+9FnEUuObmvHoh593NePzoI+aHzla+wQ6QwKQa3gzhHloN5k4vmuN2I2c+fKwNsklD3TjTw1odpRw1ggHuCC9U+oKQmG3KMGtKynvqo/qfMoPXuLgI69GQDTnEE96xB/zfS2D6tmafQ/ZYjyiFD/EHizJv2A2XMFFTQMpQLJvxo=
